services:
  gonas:
    build: .
    container_name: gonas_container
    ports:
      - 80:80
    volumes:
      - ./frontend/dist:/app/frontend/dist
      - ./contents:/app/contents
      - ./.env:/app/.env