services:
  gonas:
    build: .
    container_name: gonas_container
    ports:
      - 80:80
    volumes:
      - ./contents:/app/contents
    environment:
      - API_HOST=http://localhost/api/
      - APP_HOST=http://localhost/
      - DEV_APP_HOST=http://localhost/
      - CONTENTS_FOLDER=./contents/
      - GIN_MODE=release
      - AUTH_SECRET=
      - AUTH_REFRESH=
      - AUTH_USERNAME=
      - AUTH_PASSWORD=